### ISSUE TITLE
파일 사이즈 비교 기술조사

### ISSUE THREAD

**Issue by YunHye-Choi** [yoooolim/SE_Project2#13]
파일 사이즈 비교에는 stat구조체의 st_size라는 멤버를 사용합니다.
아래는 stat구조체와 그 멤버인 st_size가 포함하는 정보입니다.

st_size는 off_t 형으로 파일의 size를 byte단위로 저장합니다.
이때 off_t는 long과 같은 크기의 정수를 저장하는 자료형입니다.

```
// stat 구조체의 멤버 중 st_size
struct stat {
     ///생략///
     off_t             st_size;         /*total size, in byte*/
     ///생략///
};
```

**Comment by YunHye-Choi** [comment]
확인 부탁드립니다 :)

**Comment by yoooolim** [comment]
stat 구조체와 st_size 확인했습니다!

**Comment by sejung-hong** [comment]
사이즈 비교하는 함수 유익해요! 👍💯
