### ISSUE TITLE
파일 블락 수 비교 기술조사

### ISSUE THREAD

**Issue by YunHye-Choi** [yoooolim/SE_Project2#14]
파일 블락 수 비교를 할 때는 stat구조체의 st_blocks라는 멤버를 사용합니다.
아래는 stat구조체와 그 멤버인 st_blocks가 포함하는 정보입니다.

st_blocks는 blkcnt_t 형으로 파일에 할당한 블럭의 수를 저장합니다.
```
// stat 구조체의 멤버 중 st_blocks
struct stat {
     /// 생략 ////
     blkcnt_t       st_blocks;     /*number of 512B blocks allocated*/
     /// 생략 ////
};
```

**Comment by yoooolim** [comment]
stat 구조체의 st_blocks! 확인했습니다 수고하셨어요~ :>

**Comment by sejung-hong** [comment]
블락수를 비교할 때 st_blocks 멤버를 사용하네요! 👍💯
