### ISSUE TITLE
시간 정보를 가져오는 기술 조사

### ISSUE THREAD

**Issue by sejung-hong** [yoooolim/SE_Project2#19]
#include <time.h>
struct tm* localtime(const time_t *timer);

다음과 같이 localtime을 사용할 수 있다. 
지역 시간 기준으로 tm 구조체를 초기화한 후 가리키는 포인터를 리턴한다.

**Comment by yoooolim** [comment]
굳 아주 훌륭해요~

**Comment by YunHye-Choi** [comment]
오오 로컬타임 함수군요~ 훌륭한 기술조사 감사합니다.
