### ISSUE TITLE
월/일 날짜를 비교하는 기술 조사

### ISSUE THREAD

**Issue by sejung-hong** [yoooolim/SE_Project2#20]
두 개의  파일을 가져와 월/일일 비교한다.
두 개의 파일 중 어느 날이 더 이른지 출력하고 두 파일의 월/일 이 같다면 같다고 출력한다.

**Comment by yoooolim** [comment]
월/ 일을 가져오는 명령어가 뭔가요~?

**Comment by YunHye-Choi** [comment]
명령어나 함수가 조금 궁금합니당!!!

**Comment by sejung-hong** [comment]
localtime함수를 사용하여 tm구조체에서 year, mon, day를 가져올 수 있습니다.

**Comment by yoooolim** [comment]
넵 확인하였습니다~

**Comment by YunHye-Choi** [comment]
확인하였습니다~
