### ISSUE TITLE
두 개의 파일 수정 시간을 비교하는 기술 조사

### ISSUE THREAD

**Issue by sejung-hong** [yoooolim/SE_Project2#23]
두 개의  파일을 가져와 시/분을 비교한다.
두 개의 파일 중 어느 시간이 더 이른지 출력하고 두 파일의 시/분 이 같다면 같다고 출력한다.

**Comment by sejung-hong** [comment]
localtime함수를 사용하여 tm구조체에서 hour, min, sec을 받아와 비교할 수 있습니다.

**Comment by yoooolim** [comment]
넵 좋은 기술 조사네요~:>
