### ISSUE TITLE
파일 블락 수 비교 코드리뷰

### ISSUE THREAD

**Issue by YunHye-Choi** [yoooolim/SE_Project2#27]
파일 블락 수 비교 코드리뷰 부탁드립니다!!
수정 요청 사항이 있으면 말씀해주세요!

**Comment by sejung-hong** [comment]
블락수 비교 코드 확인했습니다.
수고했습니다

**Comment by yoooolim** [comment]
변수 사용 부분에서 오류가 있는 것 같습니다~ 확인 후 수정 부탁드려요~ :)

**Comment by YunHye-Choi** [comment]
확인 후 풀리퀘 하였습니다! 피드백 감사합니다.
