### ISSUE TITLE
시간 정보를 가져오는 기술  구현

### ISSUE THREAD

**Issue by sejung-hong** [yoooolim/SE_Project2#28]
localtime함수를 활용해서 시간 정보를 가져오는 함수를 구현하여 commit하였습니다.

**Comment by yoooolim** [comment]
filetime1 함수 수정이 필요할 것 같습니다~ 확인부탁드려요 :)

**Comment by yoooolim** [comment]
넵 확인했습니다~~ 🥇

**Comment by YunHye-Choi** [comment]
localtime함수군요!! 구현하신 부분 잘 확인했습니닷!
