### ISSUE TITLE
월/일 날짜를 비교하는 기술 구현

### ISSUE THREAD

**Issue by sejung-hong** [yoooolim/SE_Project2#29]
localtime함수를 활용해서 text1과 text2의 날짜 정보를 비교하여 어떤 파일이 더 이른지 확인하고 출력할 수 있습니다.
구현한 코드를 보고 확인해주세요.

**Comment by yoooolim** [comment]
datecmp 마지막 부분에 오류가 있습니다! 확인 후 수정 부탁드려요~ :D

**Comment by yoooolim** [comment]
넵 확인했습니다~ :)

**Comment by YunHye-Choi** [comment]
확인하였습니다!!
