### ISSUE TITLE
두 개의 파일 수정 시간을 비교하는 함수 구현

### ISSUE THREAD

**Issue by sejung-hong** [yoooolim/SE_Project2#30]
localtime함수를 활용해서 text1과 text2의 시간 정보를 비교하여 어떤 파일이 더 이른지 확인하고 출력할 수 있습니다.
구현한 코드를 테스트 해봐주세요

**Comment by yoooolim** [comment]
변수 사용 부분에서 살짝 오류가 있는 것 같습니다! 확인 후 수정 부탁드려요~ :D

**Comment by yoooolim** [comment]
확인했습니다~

**Comment by YunHye-Choi** [comment]
확인했습니다~
