### ISSUE TITLE
파일 수정 날짜(월/일) 비교 코드 리뷰

### ISSUE THREAD

**Issue by sejung-hong** [yoooolim/SE_Project2#35]
두 개 파일의 시간 정보를 가져와서 년, 월, 일을 비교하였습니다.
코드를 확인하고 고쳐야할 부분이나 개선할 부분 알려주세요!

**Comment by yoooolim** [comment]
datacmp 함수 마지막 부분 수정 부탁드려요~

**Comment by YunHye-Choi** [comment]
유림씨가 말씀하신 문법 오류 수정 부탁드립니다~

**Comment by sejung-hong** [comment]
넹 수정하였습니다~
