### ISSUE TITLE
두 개의 파일 수정 시간을 비교 함수 코드 리뷰

### ISSUE THREAD

**Issue by sejung-hong** [yoooolim/SE_Project2#37]
두 개 파일의 시간 정보를 가져와서 시, 분,초를 비교하였습니다.
코드를 확인하고 고쳐야할 부분이나 개선할 부분 알려주세요!

**Comment by yoooolim** [comment]
확인했습니다~

**Comment by YunHye-Choi** [comment]
시간정보 함수부분에 변수명 오류가 있네요 !! 개선 부탁드립니다~

**Comment by sejung-hong** [comment]
네 확인하였습니다~ 감사합니다~
